# use ubuntu 18.04
dist: bionic
language: python
# using python version 3.7
python:
  - "3.7"
before_install:
  - export PATH=$PATH:~/kg2-build/
# command to run tests
script:
  - bash -x ./code/kg2/setup-kg2-build.sh travisci
  - bash -x ./code/kg2/run-validation-tests.sh travisci
